#!/usr/bin/env python3
'''Clean a CSV of Python conferences and report data quality issues.

Generated by Claude (Anthropic), September 2026.

Usage:
    pip install pandas pycountry odfpy
    python clean.py
    python scrape.py   # next step

Reads ../drafts/conferences.csv (relative to this script) unless another
CSV is given. Outputs (in ../drafts):
    conferences_clean.csv      deduplicated, normalized dataset, with
                               Row (row in the input), Issues and
                               Duplicates columns for review
    inconsistencies.csv        data quality issues in the input, one per row
    potential_duplicates.csv   rows that look like the same event
    conferences_clean.ods      conferences_clean.csv formatted for review,
                               without info-level issues or the notes
                               listed in ODS_HIDDEN_ISSUES and
                               ODS_HIDDEN_DUPLICATES
'''
import argparse
import re
import unicodedata
from difflib import SequenceMatcher
from pathlib import Path
from urllib.parse import urlsplit

import pandas as pd
import pycountry
from odf.opendocument import OpenDocumentSpreadsheet
from odf.style import (
    FontFace, Style, TableCellProperties, TableColumnProperties,
    TextProperties)
from odf.table import Table, TableCell, TableColumn, TableRow
from odf.text import P

SCRIPT_FOLDER = Path(__file__).resolve().parent
DRAFTS_FOLDER = SCRIPT_FOLDER / '..' / 'drafts'
COLUMNS = [
    'Subject', 'Start Date', 'End Date', 'Location', 'Country', 'Venue',
    'Tutorial Deadline', 'Talk Deadline', 'Website URL', 'Proposal URL',
    'Sponsorship URL']
URL_COLUMNS = ['Website URL', 'Proposal URL', 'Sponsorship URL']
DATE_COLUMNS = [
    'Start Date', 'End Date', 'Tutorial Deadline', 'Talk Deadline']
ONLINE = re.compile(
    r'^(on ?line|virtual|remote|worldwide)( event)?$', re.IGNORECASE)
USA_ISSUE = 'country shortened to "USA"'
# "United States", "United States of America" or "US" as the country,
# optionally followed by "& Online" or "and Online"
UNITED_STATES = re.compile(r'\bUnited States( of America)?\b')
UK = re.compile(r'\bUK\b')
UK_ISSUE = '"UK" spelled out as "United Kingdom"'
LOCATION_ISSUE = 'place renamed'
POSTAL_ISSUE = 'postal code removed'
SERIES_COUNTRY_ISSUE = 'country added to Location'
END_YEAR_ISSUE = 'end year changed to match start year'
# "US" only as the country, optionally followed by "& Online"
US = re.compile(r'\bUS\b(?=\s*$|,?\s*(&|and)\s+(?i:online))')
NAME_ISSUE = 'name replaced with preferred form'
NUMBER_ISSUE = 'number removed from end of name'
APAC_ISSUE = '"APAC" spelled out as "Asia Pacific"'
RESPELLED_ISSUE = 'name respelled like most of its series'
# Issues that normalize() corrects in conferences_clean.csv
FIXED_ISSUES = {
    'extra whitespace', 'quotes in URL', 'URL missing http(s)://',
    'trailing slash', 'online not spelled "Online"',
    'missing, filled from Location', 'http instead of https',
    'year removed from name', '"Conf" removed from name',
    '"Conf" added to name', USA_ISSUE, RESPELLED_ISSUE,
    '"Online" removed from name', '"Worldwide" removed from name',
    APAC_ISSUE, NUMBER_ISSUE, NAME_ISSUE, UK_ISSUE, LOCATION_ISSUE,
    POSTAL_ISSUE, SERIES_COUNTRY_ISSUE, END_YEAR_ISSUE}
YEAR = re.compile(r'\b(19|20)\d{2}\b')
# Preferred names for conference series, applied anywhere in a name
NAME_ALIASES = {
    'PyCon Australia': 'PyCon AU',
    'Python Conference Austria': 'PyCon Austria',
    'Python Germany': 'PyCon DE',
    'PyCon Germany': 'PyCon DE',
    'PyCon España': 'PyConES',
    'PyCon Espana': 'PyConES',
    'PyCon ES': 'PyConES',
    'DjangoCon Australia': 'DjangoCon AU',
    'PyConEs': 'PyConES',
    'PythonFOSDEM': 'FOSDEM',
    'PyCon GR': 'PyCon Greece',
    'PyCon Hong Kong': 'PyCon HK',
    'PyCon PH': 'PyCon Philippines',
    'PyCon Slovakia': 'PyCon SK',
    'Python Machine Learning': 'PyML',
    'Python Pizza Hamburg': 'Hamburg Python Pizza',
    'Python Pizza Prague': 'Prague Python Pizza',
    'PyCon Czech Republic': 'PyCon CZ',
    'PyCon France': 'PyConFR',
    'PyCon Italy': 'PyCon Italia',
    'PyCon Japan': 'PyCon JP',
    'PyCon Latin America': 'PyCon Latam',
    'PyCon LT': 'PyCon Lithuania',
    'PyCon Poland': 'PyCon PL',
    'PyCon South Africa': 'PyConZA',
    'PyCon Spain': 'PyConES',
    'PyCon Taiwan': 'PyCon TW',
    'Python Day Mexico': 'PyDay México',
    'Python Day México': 'PyDay México',
    'PythonDay Mexico': 'PyDay México',
    'PythonDay México': 'PyDay México',
    'SciPy US': 'SciPy',
    'Python Pizza New Years Party': 'Hamburg Python Pizza',
    "Python Pizza New Year's Party": 'Hamburg Python Pizza',
    'PyConZA (South Africa)': 'PyConZA',
    'SciPy Latam': 'SciPy Latin America',
    'PyDay Cali Colombia': 'PyDay Cali',
    'PyCon KR': 'PyCon Korea',
    'PyHEP.dev': 'PyHEP',
    'Python Sul Brasil': 'Python Sul',
    '(canceled)': '(cancelled)',
    '(postponed)': '(cancelled)',
    'PyCon Kenya Conference': 'PyCon Kenya',
    'Launching Python Niger': 'Python Niger',
    'PyCamp CZ 25 beta': 'PyCamp CZ',
    'PyCon China ShangHai Branch': 'PyCon China',
    'PyCon Italia X': 'PyCon Italia',
    'Python Sul (Brazil)': 'Python Sul',
    'PyConES - Granada': 'PyConES'}
# Names containing the key are replaced entirely by the value
FULL_NAMES = {
    'PyCon MEA': 'PyCon MEA @ GlobalDevSlam',
    'FOSDEM': 'FOSDEM: Python Dev Room',
    'Kiwi PyCon': 'Kiwi PyCon'}
# Country to add to Location for a series, if it is not there already
SERIES_COUNTRY = {'PyCon TW': 'Taiwan'}
# Replacements in Location, applied anywhere in it
# Replacements in Location, applied in order, anywhere in it; a key can
# also be a compiled pattern
LOCATION_ALIASES = {
    'Panama': 'Panamá',
    'Florianópolis - SC': 'Florianópolis',
    'Global, but organizers based in USA': 'Online',
    'Global, but organizers based in United States': 'Online',
    'https://2020.pythonwebconf.com': 'Online',
    'Online (Israel)': 'Online',
    'Online & Tokyo, Japan (Public Viewing)': 'Tokyo, Japan',
    'Online from Sri Lanka': 'Sri Lanka',
    'Online (Chile)': 'Chile',
    'United Status of America': 'United States of America',
    'USA of USA': 'USA',
    'WA. USA': 'WA, USA',
    'Texas USA': 'Texas, USA',
    re.compile(r'San Francisco, CA(, (USA|United States))?$'):
        'San Francisco, California, USA',
    'Brussel': 'Brussels',
    'Bogota': 'Bogotá',
    'Czechia': 'Czech Republic',
    'Krakow': 'Kraków',
    'Sao Paulo': 'São Paulo',
    'Medellin': 'Medellín',
    'Mexico': 'México',
    'Aotearoa/New Zealand': 'Aotearoa, New Zealand',
    'Niger Republic': 'Niger',
    'St. Petersburg': 'Saint Petersburg',
    'Sevilla, España': 'Sevilla, Spain',
    'Shanghai, People Republic of China': 'Shanghai, Shanghai, China',
    'Shanghai, Shanghai, China': 'Shanghai, China',
    "Beijing, People's Republic of China": 'Beijing, China',
    'Malate, Manila': 'Manila, The Philippines',
    re.compile(r'(?<!The )\bPhilippines\b'): 'The Philippines',
    'Hong Kong, Hong Kong, Hong Kong': 'Hong Kong',
    'Hong Kong, China': 'Hong Kong',
    'Ramat-Gan, Israel': 'Ramat Gan, Tel Aviv, Israel',
    'Nairobi, Kenia': 'Nairobi, Kenya',
    'Seoul, Seoul Capital Area, South Korea': 'Seoul, South Korea',
    'UAE': 'United Arab Emirates',
    re.compile(r'(?<!The )\bNetherlands\b'): 'The Netherlands',
    'Shenzhen, Guangdong, China': 'Shenzhen, China',
    'Bratislava, Bratislava, Slovakia': 'Bratislava, Slovakia',
    'Dar Es Salaam, Tanzania': 'Dar es Salaam, Tanzania',
    'Spain': 'España',
    'Brazil': 'Brasil'}
# Postal codes: Japanese, Polish, Swedish, Dutch, Canadian, British, and
# 4 to 6 digits unless a street name follows ("12175 Visionary Way")
POSTAL_CODE = re.compile(
    r'\b\d{3}-\d{4}\b|\b\d{2}-\d{3}\b|\b\d{3} \d{2}\b|\b\d{4} [A-Z]{2}\b'
    r'|\b[A-Z]\d[A-Z] ?\d[A-Z]\d\b|\b[A-Z]{1,2}\d[A-Z\d]? ?\d ?[A-Z]{2}\b'
    r'|\b\d{4,6}\b(?!\s+\w+\s+(Way|St|Street|Road|Rd|Ave|Avenue|Drive)\b)')
# Series that share dates and places but are different conferences
SEPARATE_SERIES = [
    ('DjangoCon AU', 'PyCon AU'), ('Plone Conference', 'PyCon Sweden')]
# Notes to leave out of the .ods files (they stay in the CSVs)
ODS_HIDDEN_ISSUES = [
    'online not spelled "Online"', 'extra whitespace', 'quotes in URL']
ODS_HIDDEN_DUPLICATES = (
    'removed exact duplicates', 'removed after normalizing',
    'removed as the same event', 'removed placeholder row')
# Rows to leave out of the dataset entirely
EXCLUDED = [
    'PyWeek', '9th Conference of Scientific Python Latinamerica',
    'A Language Creator Discussion Moderated by Carol Willing']
# A number at the end, with any "#", "v" or "2k" in front of it
TRAILING_NUMBER = re.compile(r'[\s,]*(#|\bv|\b2k)?\d+$')
SHORT_YEAR = re.compile(r"['\u2018\u2019]\d{2}\b")  # "Summit'20"
ONLINE_WORD = re.compile(r'\bOnline\b', re.IGNORECASE)
WORLDWIDE = re.compile(r'\bWorldwide\b', re.IGNORECASE)
APAC = re.compile(r'\bAPAC\b')
CONF = re.compile(r'(?<!\S)Conf(?!\S)')  # "Conf" but not "Conf++"
COUNTRY_ALIASES = {
    'usa': 'USA', 'us': 'USA', 'united states': 'USA',
    'united states of america': 'USA', 'uk': 'GBR', 'england': 'GBR',
    'scotland': 'GBR', 'wales': 'GBR', 'czechia': 'CZE',
    'czech republic': 'CZE', 'russia': 'RUS', 'south korea': 'KOR',
    'korea': 'KOR', 'taiwan': 'TWN', 'iran': 'IRN', 'vietnam': 'VNM',
    'turkey': 'TUR', 'bolivia': 'BOL', 'tanzania': 'TZA', 'uae': 'ARE',
    'the netherlands': 'NLD', 'republic of korea': 'KOR',
    'the gambia': 'GMB', 'panamá': 'PAN', 'españa': 'ESP',
    'brasil': 'BRA', 'méxico': 'MEX', 'the philippines': 'PHL'}


# ---------- cleaning ----------

def clean_text(value):
    value = unicodedata.normalize('NFC', value or '')
    value = value.replace('\u00a0', ' ').strip()
    return re.sub(r'\s+', ' ', value)


def tidy(value):
    '''Clean up the gaps left after removing a word from a name.'''
    value = re.sub(r'\([\s-]*\)', '', value)  # "(2020)" left "()"
    value = re.sub(r'\(\s*-?\s*', '(', value)  # "(Online-Worldwide)"
    value = re.sub(r'\s+([:,.)])', r'\1', value)
    return clean_text(value).strip(' -:,')


def whole(name, flags=0):
    '''Pattern matching name as a whole word, even if it starts or ends
    with punctuation, like "PyConZA (South Africa)".'''
    return re.compile(rf'(?<!\w){re.escape(name)}(?!\w)', flags)


def is_excluded(subject):
    return any(
        whole(name, re.IGNORECASE).search(subject) for name in EXCLUDED)


def remove_words(value):
    '''Drop the year (including "'20"), "Online" and "Worldwide":
    "FOSDEM 2020: Python Dev Room" -> "FOSDEM: Python Dev Room"'''
    for pattern in (YEAR, SHORT_YEAR, ONLINE_WORD, WORLDWIDE):
        value = pattern.sub('', value)
    return tidy(value)


def strip_words(value):
    '''remove_words, then apply NAME_ALIASES and FULL_NAMES and spell
    out "APAC": "PyCon APAC 2023" -> "PyCon Asia Pacific"'''
    value = remove_words(value)
    for name, preferred in NAME_ALIASES.items():
        value = whole(name).sub(preferred, value)
    for name, full_name in FULL_NAMES.items():
        if whole(name).search(value):
            value = full_name
    return tidy(APAC.sub('Asia Pacific', value))


def clean_subject(value):
    '''strip_words, then drop any number at the end: "PyCon IT 9" ->
    "PyCon IT", "PiterPy #5" -> "PiterPy", "csv,conf,v8" -> "csv,conf"'''
    return tidy(TRAILING_NUMBER.sub('', strip_words(value)))


def harmonize_conf(subjects):
    '''Within each series, add or remove the word "Conf" to match most
    of its rows; leave ties alone. Return (subjects, notes), where notes
    maps row index -> explanation for each changed row.'''
    subjects = subjects.copy()
    notes = {}
    has_conf = subjects.map(lambda v: bool(CONF.search(v)))
    for key, group in subjects.groupby(subjects.map(base_name)):
        with_conf = has_conf[group.index]
        count, total = with_conf.sum(), len(group)
        if not key or count in (0, total) or count * 2 == total:
            continue
        detail = f'{count} of {total} rows in this series have "Conf"'
        if count * 2 < total:
            for index in group.index[with_conf]:
                subjects[index] = tidy(CONF.sub('', subjects[index]))
                notes[index] = ('"Conf" removed from name', detail)
            continue
        # Insert "Conf" where the most common spelling has it
        target = group[with_conf].value_counts().index[0]
        prefix = tidy(CONF.sub('', target))
        for index in group.index[~with_conf]:
            if (value := subjects[index]).startswith(prefix):
                subjects[index] = target + value[len(prefix):]
                notes[index] = ('"Conf" added to name', detail)
    return subjects, notes


def harmonize_spelling(subjects):
    '''Within each series of names that match ignoring case, spaces and
    punctuation ("Piter Py", "PiterPy"), use the preferred name from
    NAME_ALIASES if there is one, else the most common spelling; leave
    ties alone. Return (subjects, notes) like harmonize_conf.'''
    subjects = subjects.copy()
    notes = {}
    preferred = {
        fold(name): name
        for name in [*NAME_ALIASES.values(), *FULL_NAMES.values()]}
    for key, group in subjects.groupby(subjects.map(fold)):
        spellings = group.value_counts()
        if not key or len(spellings) < 2:
            continue
        if target := preferred.get(key):
            detail = f'{target}: preferred name'
        elif spellings.iloc[0] == spellings.iloc[1]:
            continue
        else:
            target, count = spellings.index[0], spellings.iloc[0]
            detail = f'{target}: {count} of {len(group)} rows in this series'
        for index in group.index[group != target]:
            notes[index] = (RESPELLED_ISSUE, detail)
            subjects[index] = target
    return subjects, notes


def harmonize_subjects(subjects):
    '''Apply harmonize_conf, then harmonize_spelling. Return (subjects,
    notes), where notes maps row index -> list of (issue, detail).'''
    subjects, conf_notes = harmonize_conf(subjects)
    subjects, spelling_notes = harmonize_spelling(subjects)
    notes = {}
    for index in [*conf_notes, *spelling_notes]:
        notes[index] = [
            n[index] for n in (conf_notes, spelling_notes) if index in n]
    return subjects, notes


def clean_url(value):
    value = clean_text(value).strip('\u201c\u201d"\' ')
    value = re.sub(r'^http://', 'https://', value, flags=re.IGNORECASE)
    if value and not re.match(r'https://|mailto:', value, re.IGNORECASE):
        value = 'https://' + value
    return value.rstrip('/')


def location_pattern(name):
    return name if isinstance(name, re.Pattern) else whole(name)


def rename_places(value):
    for name, preferred in LOCATION_ALIASES.items():
        value = location_pattern(name).sub(preferred, value)
    return value


def remove_postal_codes(value):
    value = POSTAL_CODE.sub('', value)
    value = re.sub(r'\s*,(\s*,)+', ',', value)  # "27,,51105 Köln"
    value = re.sub(r'\s*,\s*', ', ', value)
    return clean_text(value).strip(' ,')


def clean_location(value):
    '''Rename places, remove postal codes and spell countries
    consistently. Renaming runs before and after the USA and UK
    changes, so it sees both spellings.'''
    value = remove_postal_codes(rename_places(clean_text(value)))
    value = US.sub('USA', UNITED_STATES.sub('USA', value))
    value = rename_places(UK.sub('United Kingdom', value))
    return 'Online' if ONLINE.match(value) else value


def to_alpha3(value):
    if not (value := clean_text(value)):
        return ''
    if alias := COUNTRY_ALIASES.get(value.lower()):
        return alias
    try:
        return pycountry.countries.lookup(value).alpha_3
    except LookupError:
        try:
            return pycountry.countries.search_fuzzy(value)[0].alpha_3
        except LookupError:
            return ''


def is_country(value):
    '''True for a country name or code, e.g. "Brazil", "USA", "UK";
    two-letter codes only if they are in COUNTRY_ALIASES, since "CA"
    is more likely California than Canada.'''
    if value.lower() in COUNTRY_ALIASES:
        return True
    if len(value) <= 2:
        return False
    try:
        pycountry.countries.lookup(value)
    except LookupError:
        return False
    return True


def country_name(alpha3):
    country = pycountry.countries.get(alpha_3=alpha3)
    return country.name if country else ''


def strip_online(location):
    '''"Basel, Switzerland & Online" -> "Basel, Switzerland".'''
    return re.sub(
        r',?\s*(&|and)\s*online.*$', '', location, flags=re.IGNORECASE)


def country_from_location(location):
    if not location or location == 'Online':
        return ''
    last = strip_online(location).split(',')[-1].strip()
    if last.isupper() and len(last) == 2 and \
            last.lower() not in COUNTRY_ALIASES:
        return ''  # 'CA' is more likely California than Canada
    return to_alpha3(last)


def fix_end_year(start, end):
    '''If end is before start, give it the start's year; return end as
    is when either date is not YYYY-MM-DD or the fix is impossible.'''
    if not (re.fullmatch(r'\d{4}-\d{2}-\d{2}', start or '') and
            re.fullmatch(r'\d{4}-\d{2}-\d{2}', end or '')) or end >= start:
        return end
    fixed = start[:4] + end[4:]
    return fixed if pd.notna(pd.to_datetime(fixed, errors='coerce')) \
        else end


def normalize(df):
    df = df.copy()
    for column in COLUMNS:
        df[column] = df[column].map(clean_text)
    for column in URL_COLUMNS:
        df[column] = df[column].map(clean_url)
    df['Subject'], _ = harmonize_subjects(
        df['Subject'].map(clean_subject))
    df['Location'] = df['Location'].map(clean_location)
    df['End Date'] = [
        fix_end_year(a, b) for a, b in zip(df['Start Date'], df['End Date'])]
    for series, country in SERIES_COUNTRY.items():
        rows = (df['Subject'] == series) & \
            ~df['Location'].str.contains(country, regex=False)
        df.loc[rows, 'Location'] = df.loc[rows, 'Location'].map(
            lambda v: f'{v}, {country}' if v else country)
    missing = df['Country'] == ''
    df.loc[missing, 'Country'] = df.loc[missing, 'Location'].map(
        country_from_location)
    return df


# ---------- inconsistencies ----------

def fold(value):
    '''Lowercase ASCII form, so "Kraków" and "Krakow" compare equal.'''
    value = unicodedata.normalize('NFKD', value)
    value = value.encode('ascii', 'ignore').decode()
    return re.sub(r'[^a-z0-9]', '', value.lower())


def is_similar(a, b, min_ratio):
    return SequenceMatcher(None, a, b).ratio() >= min_ratio


def find_city_misspellings(locations, min_ratio=0.85):
    '''Map row index -> (city, likely spelling), within each country.'''
    cities = pd.DataFrame({
        'city': locations.map(lambda v: v.split(',')[0].strip()),
        'country': locations.map(country_from_location)})
    cities = cities[(cities['city'] != '') & (cities['country'] != '')]
    counts = cities.value_counts()
    corrections = {}
    for (city, country), count in counts.items():
        rivals = [
            (other_count, len(other), other)
            for (other, other_country), other_count in counts.items()
            if other_country == country and other != city
            and (other_count, len(other)) > (count, len(city))
            and is_similar(fold(city), fold(other), min_ratio)]
        if rivals:
            corrections[city, country] = max(rivals)[2]
    return {
        index: (row.city, better)
        for index, row in cities.iterrows()
        if (better := corrections.get((row.city, row.country)))}


def find_inconsistencies(raw, max_event_days=14):
    '''Check the raw CSV; row numbers match the file (header is row 1).'''
    issues = []

    def add(index, column, severity, issue, value='', detail=''):
        issues.append({
            'row': index + 2, 'column': column, 'severity': severity,
            'issue': issue, 'value': value, 'detail': detail})

    subjects, subject_notes = harmonize_subjects(
        raw['Subject'].map(clean_text).map(clean_subject))
    first_seen = {}
    for index, row in raw.iterrows():
        if not any(row):
            add(index, '', 'error', 'blank row')
            continue
        if (key := tuple(row)) in first_seen:
            add(index, '', 'warning', 'exact duplicate',
                detail=f'same as row {first_seen[key] + 2}')
            continue
        first_seen[key] = index

        for column, value in row.items():
            if value != value.strip() or '  ' in value:
                add(index, column, 'warning', 'extra whitespace', value)

        # Dates
        dates = {}
        for column in DATE_COLUMNS:
            if not (value := row[column]):
                continue
            parsed = pd.to_datetime(value, errors='coerce')
            if not re.fullmatch(r'\d{4}-\d{2}-\d{2}', value) or \
                    pd.isna(parsed):
                add(index, column, 'error',
                    'not a valid YYYY-MM-DD date', value)
            else:
                dates[column] = parsed
        start, end = dates.get('Start Date'), dates.get('End Date')
        if not row['Start Date']:
            add(index, 'Start Date', 'warning', 'missing start date')
        elif not row['End Date']:
            add(index, 'End Date', 'warning', 'missing end date')
        if start is not None and end is not None:
            if end < start:
                fixed = fix_end_year(row['Start Date'], row['End Date'])
                if fixed >= row['Start Date']:
                    add(index, 'End Date', 'info', END_YEAR_ISSUE,
                        row['End Date'], fixed)
                else:
                    add(index, 'End Date', 'error',
                        'end date before start date', row['End Date'])
            elif (days := (end - start).days) > max_event_days:
                add(index, 'End Date', 'warning',
                    f'event longer than {max_event_days} days',
                    row['End Date'], f'{days} days')
        for column in ('Tutorial Deadline', 'Talk Deadline'):
            deadline = dates.get(column)
            if start is not None and deadline is not None and \
                    deadline > start:
                add(index, column, 'error',
                    'deadline after start date', row[column])
        year = YEAR.search(row['Subject'])
        if year and row['Start Date'] and \
                year[0] != row['Start Date'][:4]:
            add(index, 'Subject', 'error',
                'year in name does not match start date',
                row['Subject'], row['Start Date'])

        # Subject
        if not row['Subject']:
            add(index, 'Subject', 'error', 'missing name')
        status = re.search(
            r'cancel+ed|postponed', row['Subject'], re.IGNORECASE)
        if status:
            add(index, 'Subject', 'info', 'status stored in name',
                row['Subject'], status[0])
        if TRAILING_NUMBER.search(strip_words(clean_text(row['Subject']))):
            add(index, 'Subject', 'info', NUMBER_ISSUE, row['Subject'])
        if YEAR.search(row['Subject']) or SHORT_YEAR.search(row['Subject']):
            add(index, 'Subject', 'info', 'year removed from name',
                row['Subject'])
        for word, pattern in (('Online', ONLINE_WORD),
                              ('Worldwide', WORLDWIDE)):
            if pattern.search(row['Subject']):
                add(index, 'Subject', 'info',
                    f'"{word}" removed from name', row['Subject'])
        if is_excluded(row['Subject']):
            add(index, 'Subject', 'info', 'row excluded', row['Subject'])
        bare = remove_words(clean_text(row['Subject']))
        for name, preferred in [*NAME_ALIASES.items(), *FULL_NAMES.items()]:
            if whole(name).search(bare):
                add(index, 'Subject', 'info', NAME_ISSUE, row['Subject'],
                    f'{name} -> {preferred}')
        if APAC.search(row['Subject']):
            add(index, 'Subject', 'info', APAC_ISSUE, row['Subject'])
        for issue, detail in subject_notes.get(index, []):
            add(index, 'Subject', 'info', issue, row['Subject'], detail)


        # URLs
        if not row['Website URL']:
            add(index, 'Website URL', 'warning', 'missing website URL')
        for column in URL_COLUMNS:
            if not (value := row[column].strip()):
                continue
            if re.search('[\u201c\u201d"\']', value):
                add(index, column, 'error', 'quotes in URL', value)
            elif not re.match(r'https?://|mailto:', value):
                add(index, column, 'error',
                    'URL missing http(s)://', value)
            elif value.startswith('http://'):
                add(index, column, 'info', 'http instead of https', value)
            path = urlsplit(value.strip('\u201c\u201d')).path
            if value.endswith('/') and path == '/':
                add(index, column, 'info', 'trailing slash', value)

        # Location and country
        location = clean_text(row['Location'])
        if not location:
            add(index, 'Location', 'warning', 'missing location')
        elif ONLINE.match(location) and location != 'Online':
            add(index, 'Location', 'warning',
                'online not spelled "Online"', location)
        elif location != 'Online' and \
                re.search(r'online', location, re.IGNORECASE):
            add(index, 'Location', 'info',
                'hybrid event mixed into location', location)
        if UNITED_STATES.search(location) or US.search(location):
            add(index, 'Location', 'info', USA_ISSUE, location)
        if UK.search(location):
            add(index, 'Location', 'info', UK_ISSUE, location)
        for name, preferred in LOCATION_ALIASES.items():
            if match := location_pattern(name).search(location):
                add(index, 'Location', 'info', LOCATION_ISSUE, location,
                    f'{match[0]} -> {preferred}')
        if codes := [m[0] for m in POSTAL_CODE.finditer(location)]:
            add(index, 'Location', 'info', POSTAL_ISSUE, location,
                ', '.join(codes))
        country = SERIES_COUNTRY.get(subjects[index])
        if country and country not in location:
            add(index, 'Location', 'info', SERIES_COUNTRY_ISSUE, location,
                country)
        if re.search(r'\d{3,}', location):
            add(index, 'Location', 'warning',
                'looks like a street address, belongs in Venue?',
                location)
        if re.search(r'rotating|^(europe|africa|asia)$', location,
                     re.IGNORECASE):
            add(index, 'Location', 'warning',
                'placeholder location', location)
        cleaned = strip_online(clean_location(location))
        last = cleaned.split(',')[-1].strip()
        if cleaned not in ('', 'Online') and not is_country(last):
            add(index, 'Location', 'warning',
                'last part is not a country name', location, last)
        derived = country_from_location(clean_location(location))
        if not row['Country'] and derived:
            add(index, 'Country', 'info',
                'missing, filled from Location', '', derived)
        elif row['Country'] and derived and row['Country'] != derived:
            add(index, 'Country', 'error',
                'does not match Location', row['Country'], derived)

    # Country spelling variants, e.g. USA / United States / US
    locations = raw['Location'].map(clean_location).map(strip_online)
    last = locations.map(lambda v: v.split(',')[-1].strip())
    groups = pd.DataFrame({'value': last, 'key': last.map(to_alpha3)})
    groups = groups[(groups['key'] != '') & (groups['value'] != '')]
    for _, group in groups.groupby('key'):
        if (spellings := group['value'].value_counts()).size > 1:
            preferred = spellings.index[0]
            for index in group.index[group['value'] != preferred]:
                add(index, 'Location', 'warning',
                    'country spelled differently elsewhere',
                    raw.at[index, 'Location'],
                    f'most common: {preferred}')

    # City variants and near misses, e.g. Kraków / Krakow, Hydrabad
    for index, (city, better) in find_city_misspellings(locations).items():
        add(index, 'Location', 'warning',
            'city spelled differently elsewhere',
            raw.at[index, 'Location'], f'{city} -> {better}')

    return pd.DataFrame(issues)


# ---------- duplicates ----------

def base_name(subject):
    '''Series name without year, status or "Conf":
    "AfroPython Conf 2025 (canceled)" -> "afropython".'''
    subject = re.sub(
        r'\((cancel+ed|postponed|online|virtual)\)', '', subject,
        flags=re.IGNORECASE)
    return fold(CONF.sub('', YEAR.sub('', subject)))


def describe_gap(a, b):
    '''"1 day", "2-7 days" or "over a week"; None if a date is invalid.'''
    days = pd.to_datetime(b, errors='coerce') - \
        pd.to_datetime(a, errors='coerce')
    if pd.isna(days):
        return None
    if (gap := abs(days.days)) == 1:
        return '1 day'
    return '2-7 days' if gap <= 7 else 'over a week'


def describe_differences(a, b):
    '''List (column, label, detail) for each column where a and b differ.'''
    notes = []
    for column in COLUMNS:
        if (x := a[column]) == (y := b[column]):
            continue
        if not x or not y:
            label = f'{column} missing in one'
        elif column == 'Subject' and base_name(x) == base_name(y):
            label = 'name spelled differently'
        elif column in DATE_COLUMNS and (gap := describe_gap(x, y)):
            label = f'{column} differs by {gap}'
        elif column == 'Location' and \
                fold(x.split(',')[0]) == fold(y.split(',')[0]) and \
                country_from_location(x) == country_from_location(y):
            label = 'Location formatted differently'
        else:
            label = f'{column} differs'
        notes.append((column, label, f'{x or "(blank)"} | {y or "(blank)"}'))
    return notes


def group_pairs(pairs):
    '''Merge overlapping pairs into groups: (A, B), (B, C) -> {A, B, C}.'''
    parent = {}

    def root(i):
        while (p := parent.get(i, i)) != i:
            i = p
        return i

    for i, j in pairs:
        parent[root(j)] = root(i)
    groups = {}
    for i, j in pairs:
        groups.setdefault(root(i), set()).update((i, j))
    return list(groups.values())


def find_potential_duplicates(df, max_days=3, min_ratio=0.85):
    '''Group rows starting within max_days of each other whose names
    match closely, or loosely if they are in the same city.'''
    rows = df.assign(
        series=df['Subject'].map(base_name),
        start=pd.to_datetime(df['Start Date'], errors='coerce'),
        city=df['Location'].map(lambda v: fold(v.split(',')[0])))
    rows = rows.dropna(subset=['start'])
    separate = [{base_name(a), base_name(b)} for a, b in SEPARATE_SERIES]
    pairs = []
    for _, group in rows.groupby(rows['start'].dt.year):
        records = list(group.itertuples())
        for i, a in enumerate(records):
            for b in records[i + 1:]:
                if abs((a.start - b.start).days) > max_days:
                    continue
                if {a.series, b.series} in separate:
                    continue
                ratio = SequenceMatcher(None, a.series, b.series).ratio()
                same_city = a.city and a.city == b.city
                if ratio >= min_ratio or (same_city and ratio >= 0.5):
                    pairs.append((a.Index, b.Index, round(ratio, 2)))

    groups = [
        {'rows': rows, 'ratio': min(
            ratio for i, _, ratio in pairs if i in rows)}
        for rows in group_pairs([(i, j) for i, j, _ in pairs])]

    report, issues = [], []
    for group_id, group in enumerate(groups, 1):
        first, *others = sorted(group['rows'])
        for index in [first, *others]:
            notes = describe_differences(df.loc[first], df.loc[index])
            report.append({
                'group': group_id, 'row': index + 2,
                'similarity': group['ratio'],
                'differences': ', '.join(label for _, label, _ in notes),
                **df.loc[index, COLUMNS].to_dict()})
            issues += [{
                'row': index + 2, 'column': column, 'severity': 'warning',
                'issue': f'potential duplicate: {label}', 'value': '',
                'detail': f'vs row {first + 2}: {detail}',
            } for column, label, detail in notes]
    return pd.DataFrame(report), pd.DataFrame(issues)


# ---------- output ----------

def write_ods(
        df, path, wide_columns=('Issues', 'Duplicates'),
        tight_columns=('Row', 'Start Date', 'End Date')):
    '''Save df as an .ods spreadsheet with top-aligned, wrapped text in
    every cell and one line per newline. Columns are 1" wide, except
    the wide_columns, which are 3" wide, and the tight_columns, which
    are just wide enough for their contents.'''
    doc = OpenDocumentSpreadsheet()
    doc.fontfacedecls.addElement(FontFace(
        name='Arial', fontfamily='Arial', fontfamilygeneric='swiss'))

    def add_style(name, family, *properties):
        style = Style(name=name, family=family)
        for element in properties:
            style.addElement(element)
        doc.automaticstyles.addElement(style)
        return style

    narrow = add_style(
        'narrow', 'table-column', TableColumnProperties(columnwidth='1in'))
    wide = add_style(
        'wide', 'table-column', TableColumnProperties(columnwidth='3in'))
    wrap = add_style(
        'wrap', 'table-cell', TextProperties(fontname='Arial'),
        TableCellProperties(wrapoption='wrap', verticalalign='top'))

    def column_style(column):
        if column in wide_columns:
            return wide
        if column not in tight_columns:
            return narrow
        # About 0.08" per digit in 10pt Arial, plus cell padding;
        # the header may wrap, but not in the middle of a word
        values = df[column].astype(str)
        characters = max(
            values.str.len().max(), *map(len, column.split()))
        return add_style(
            f"tight-{column.replace(' ', '-')}", 'table-column',
            TableColumnProperties(
                columnwidth=f'{0.08 * characters + 0.1:.2f}in'))

    table = Table(name=path.stem)
    for column in df.columns:
        table.addElement(TableColumn(stylename=column_style(column)))
    for values in [list(df.columns), *df.itertuples(index=False)]:
        row = TableRow()
        for column, value in zip(df.columns, values):
            if (value := str(value)).isdigit():
                cell = TableCell(
                    valuetype='float', value=value, stylename=wrap)
            else:
                cell = TableCell(valuetype='string', stylename=wrap)
            for line in value.splitlines():
                cell.addElement(P(text=line))
            row.addElement(cell)
        table.addElement(row)
    doc.spreadsheet.addElement(table)
    doc.save(str(path))


def for_review(df):
    '''Copy of df for the .ods file, leaving out info-level issues,
    the ODS_HIDDEN_ISSUES and the ODS_HIDDEN_DUPLICATES notes.'''
    def keep_issue(line):
        return not line.startswith('info') and \
            not any(issue in line for issue in ODS_HIDDEN_ISSUES)

    def keep_duplicate(line):
        return not line.startswith(ODS_HIDDEN_DUPLICATES)

    df = df.copy()
    for column, keep in (('Issues', keep_issue),
                         ('Duplicates', keep_duplicate)):
        if column in df:
            df[column] = df[column].map(lambda v: '\n'.join(
                line for line in v.split('\n') if keep(line)))
    return df


# ---------- row comments ----------

def describe_issues(issues, row):
    '''"error [End Date]: end date before start date", one per line.'''
    notes = []
    for issue in issues[issues['row'] == row].itertuples():
        note = f'{issue.severity}'
        note += f' [{issue.column}]: ' if issue.column else ': '
        note += issue.issue
        if issue.detail:
            note += f' ({issue.detail})'
        if issue.issue in FIXED_ISSUES:
            note += ' [fixed]'
        notes.append(note)
    return '\n'.join(notes)


def drop_same_events(df, max_days=7):
    '''Remove rows that are the same event as another row, keeping the
    one with the most columns filled (the earliest on a tie). Two rows
    are the same event if either
    - their Subjects match ignoring case, spaces and punctuation
      ("Piter Py" = "PiterPy") and both dates are the same
    - or their Subjects match exactly, their Start Dates are within
      max_days of each other, and so are their End Dates (or one is
      blank)
    Return the kept rows and a map of kept index -> removed indexes.'''
    filled = (df[COLUMNS] != '').sum(axis=1)
    start = pd.to_datetime(df['Start Date'], errors='coerce')
    end = pd.to_datetime(df['End Date'], errors='coerce')

    def gap(dates, i, j):
        days = abs((dates[i] - dates[j]).days)
        return None if pd.isna(days) else days

    def is_same(i, j):
        start_gap, end_gap = gap(start, i, j), gap(end, i, j)
        if start_gap is None:
            return False
        if start_gap == 0 and df.at[i, 'End Date'] == df.at[j, 'End Date']:
            return True
        return df.at[i, 'Subject'] == df.at[j, 'Subject'] and \
            start_gap <= max_days and \
            (end_gap is None or end_gap <= max_days)

    pairs = []
    dated = df[df['Start Date'] != '']
    for _, group in dated.groupby(dated['Subject'].map(fold)):
        rows = list(group.index)
        pairs += [
            (i, j) for n, i in enumerate(rows) for j in rows[n + 1:]
            if is_same(i, j)]
    same = {}
    for rows in group_pairs(pairs):
        best = max(rows, key=lambda i: (filled[i], -i))
        same[best] = sorted(rows - {best})
    dropped = [i for others in same.values() for i in others]
    return df.drop(index=dropped), same


def merge_cancelled(df):
    '''Remove each "(cancelled)" row that has a row in the same series
    with the same Start Date, and add "(cancelled)" to that row instead.
    Return the kept rows and a map of kept index -> notes.'''
    df = df.copy()
    cancelled = df['Subject'].str.contains('(cancelled)', regex=False)
    keys = df['Subject'].map(base_name)
    notes, dropped = {}, []
    for i in df.index[cancelled]:
        matches = df.index[
            ~cancelled & (keys == keys[i]) & (df['Start Date'] != '') &
            (df['Start Date'] == df.at[i, 'Start Date'])]
        if matches.empty:
            continue
        j = matches[0]
        if '(cancelled)' not in df.at[j, 'Subject']:
            df.at[j, 'Subject'] += ' (cancelled)'
        notes.setdefault(j, []).append(
            f'removed cancelled row {i + 2} and marked this row cancelled')
        dropped.append(i)
    return df.drop(index=dropped), notes


def drop_placeholders(df):
    '''Remove rows with a "rotating" Location, or with no Start Date,
    when another row has the same Subject (with a Start Date, for rows
    without one). Return the kept rows and a map of kept index -> notes.'''
    rotating = df['Location'].str.contains('rotating', case=False)
    undated = df['Start Date'] == ''
    notes, dropped = {}, []
    for i in df.index[rotating | undated]:
        others = df.index[
            (df['Subject'] == df.at[i, 'Subject']) & (df.index != i) &
            ~df.index.isin(dropped)]
        if undated[i]:
            others = others[~undated[others]]
        if others.empty:
            continue
        # Attach the note to a row that will stay, if there is one
        if not (real := others[~(rotating | undated)[others]]).empty:
            others = real
        reason = 'rotating location' if rotating[i] else 'no start date'
        notes.setdefault(others[0], []).append(
            f'removed placeholder row {i + 2} ({reason})')
        dropped.append(i)
    return df.drop(index=dropped), notes


def describe_duplicates(
        raw, normalized, removed, same, extra, duplicates, index):
    '''Removed and possible duplicates of one kept row.'''
    notes = [*extra.get(index, [])]
    for other in same.get(index, []):
        note = f'removed as the same event: row {other + 2}'
        differences = describe_differences(
            normalized.loc[index], normalized.loc[other])
        labels = [
            f"named {normalized.at[other, 'Subject']}"
            if column == 'Subject' else label
            for column, label, _ in differences]
        if labels:
            note += f" ({', '.join(labels)})"
        if twins := removed.get(other):
            note += f', which replaced {join_rows([i + 2 for i in twins])}'
        notes.append(note)
    twins = removed.get(index, [])
    exact = [i + 2 for i in twins if raw.loc[i].equals(raw.loc[index])]
    other = [i + 2 for i in twins if i + 2 not in exact]
    if exact:
        notes.append(f'removed exact duplicates: {join_rows(exact)}')
    if other:
        notes.append(
            f'removed after normalizing: {join_rows(other)}')
    if duplicates.empty:
        return '\n'.join(notes)
    for match in duplicates[duplicates['row'] == index + 2].itertuples():
        group = duplicates[duplicates['group'] == match.group]
        others = [r for r in group['row'] if r != index + 2]
        note = f'possible duplicate of {join_rows(others)}'
        if match.differences:
            note += f' ({match.differences})'
        notes.append(note)
    return '\n'.join(notes)


def join_rows(rows):
    '''[5] -> "row 5", [5, 7] -> "rows 5, 7".'''
    label = 'row' if len(rows) == 1 else 'rows'
    return f"{label} {', '.join(str(r) for r in rows)}"


def order_rows(df, duplicates):
    '''Sort by name and date, keeping potential duplicates together
    at the position of the group's first member.'''
    df = df.sort_values(
        ['Subject', 'Start Date'], key=lambda s: s.str.lower())
    position = pd.Series(range(len(df)), index=df.index + 2)
    group_position = position.copy()
    if not duplicates.empty:
        groups = duplicates.set_index('row')['group']
        first = position[groups.index].groupby(groups.values).min()
        group_position[groups.index] = groups.map(first).values
    order = pd.DataFrame({
        'group': group_position.values, 'position': position.values})
    return df.iloc[order.sort_values(['group', 'position']).index]


def main():
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument(
        'csv', type=Path, nargs='?',
        default=DRAFTS_FOLDER / 'conferences.csv')
    args = parser.parse_args()
    DRAFTS_FOLDER.mkdir(parents=True, exist_ok=True)

    raw = pd.read_csv(args.csv, dtype=str, keep_default_na=False)[COLUMNS]
    print(f'{len(raw)} rows read')

    # 1. Exact duplicates, then ones that differed only by whitespace,
    # quotes or trailing slashes; remember which kept row each replaced
    blank = ~(raw != '').any(axis=1)
    excluded = raw['Subject'].map(is_excluded)
    raw_kept = raw[~blank & ~excluded]
    normalized = normalize(raw_kept)
    kept, removed = {}, {}
    for index, key in zip(normalized.index, normalized.itertuples(
            index=False, name=None)):
        if (first := kept.setdefault(key, index)) != index:
            removed.setdefault(first, []).append(index)
    df = normalized.loc[list(kept.values())]
    exact_count = raw_kept.duplicated().sum()
    print(f'{blank.sum()} blank rows removed')
    print(f'{excluded.sum()} excluded rows removed')
    print(f'{exact_count} exact duplicates removed')
    print(f'{len(normalized) - len(df) - exact_count} more duplicates '
          'removed after normalizing')

    # 2. Same event: keep the row with more filled in
    df, same = drop_same_events(df)
    print(f'{sum(map(len, same.values()))} rows removed as the same '
          'event')

    # 3. Cancelled rows and placeholders
    df, cancelled = merge_cancelled(df)
    print(f'{sum(map(len, cancelled.values()))} cancelled rows merged')
    df, placeholders = drop_placeholders(df)
    print(f'{sum(map(len, placeholders.values()))} placeholder rows '
          'removed')
    extra = {}
    for notes in (cancelled, placeholders):
        for index, lines in notes.items():
            extra.setdefault(index, []).extend(lines)

    # 4. Potential duplicates
    duplicates, duplicate_issues = find_potential_duplicates(df)
    duplicates.to_csv(
        DRAFTS_FOLDER / 'potential_duplicates.csv', index=False)
    print(f"{duplicates['group'].nunique()} potential duplicates flagged")

    # 5. Inconsistencies
    row_issues = find_inconsistencies(raw)
    issues = pd.concat([row_issues, duplicate_issues], ignore_index=True)
    issues = issues.sort_values(['row', 'column'], kind='stable')
    issues.to_csv(DRAFTS_FOLDER / 'inconsistencies.csv', index=False)
    print(f'{len(issues)} inconsistencies found:')
    counts = issues.groupby(['severity', 'issue']).size()
    print(counts.sort_values(ascending=False).to_string())

    # 6. Comment columns, so each row can be reviewed on its own
    df = df.assign(
        Row=df.index + 2,
        Issues=[describe_issues(row_issues, i + 2) for i in df.index],
        Duplicates=[
            describe_duplicates(
                raw, normalized, removed, same, extra, duplicates, i)
            for i in df.index])
    df = order_rows(df, duplicates)
    df = df[['Row', *COLUMNS, 'Issues', 'Duplicates']]
    df.to_csv(DRAFTS_FOLDER / 'conferences_clean.csv', index=False)
    write_ods(for_review(df), DRAFTS_FOLDER / 'conferences_clean.ods')
    print(f'{len(df)} rows written to {DRAFTS_FOLDER.resolve()}')


if __name__ == '__main__':
    main()
