#!/usr/bin/env python3
'''Update the cleaned conference CSV from each website and a web search.

Generated by Claude (Anthropic), September 2026.

Usage:
    pip install httpx beautifulsoup4 lxml pandas pycountry odfpy ddgs
    python clean.py   # previous step
    python scrape.py
    python scrape.py --skip-search --limit 20

Reads ../drafts/conferences_clean.csv (relative to this script) unless
another CSV is given. Outputs (in ../drafts):
    conferences_updated.csv   cleaned dataset with scraped values filled
                              in, new editions added, and an Updates
                              column noting each change and its source
    updates.csv               every filled cell, added row and conflict,
                              with its source (row numbers match the Row
                              column)
    conferences_updated.ods   same as conferences_updated.csv, formatted
                              for review
    cache.json                fetched pages and searches, so reruns are
                              fast and resumable
'''
import argparse
import json
import re
import time
from datetime import date
from difflib import SequenceMatcher
from pathlib import Path

import httpx
import pandas as pd
from bs4 import BeautifulSoup

from clean import (
    COLUMNS, DATE_COLUMNS, DRAFTS_FOLDER, YEAR, base_name, clean_location,
    clean_subject, clean_text, clean_url, country_from_location,
    country_name, harmonize_conf, is_similar, to_alpha3, write_ods)

EVENT_TYPES = {'Event', 'ConferenceEvent', 'EducationEvent', 'Hackathon'}
REQUEST_DELAY = 1  # seconds between requests
HEADERS = {'User-Agent': 'Mozilla/5.0 (conference-dataset-updater)'}
LINK_PATTERNS = {
    'Proposal URL': (
        r'call for (papers|proposals|speakers)|\bcfp\b'
        r'|submit a (talk|proposal)'),
    'Sponsorship URL': r'\bsponsor(ship|s|ing)?\b|patrocin'}


# ---------- schema.org extraction ----------

def iter_jsonld(soup):
    for tag in soup.find_all('script', type='application/ld+json'):
        try:
            data = json.loads(tag.string or '')
        except json.JSONDecodeError:
            continue
        stack = data if isinstance(data, list) else [data]
        while stack:
            if isinstance(item := stack.pop(), dict):
                stack += [
                    v for v in item.values()
                    if isinstance(v, (dict, list))]
                yield item
            elif isinstance(item, list):
                stack += item


def type_name(value):
    '''"https://schema.org/ConferenceEvent" -> "ConferenceEvent".'''
    return str(value).rstrip('/').rsplit('/', 1)[-1]


def iter_microdata(soup):
    for tag in soup.select('[itemtype*="schema.org"]'):
        if type_name(tag.get('itemtype', '')) not in EVENT_TYPES:
            continue
        item = {'@type': type_name(tag['itemtype'])}
        for prop in tag.select('[itemprop]'):
            value = prop.get('content') or prop.get('datetime') or \
                prop.get('href') or prop.get_text(' ', strip=True)
            item.setdefault(prop['itemprop'], value)
        yield item


def is_event(item):
    types = item.get('@type', [])
    types = types if isinstance(types, list) else [types]
    return bool(EVENT_TYPES & {type_name(t) for t in types})


def text_of(value):
    if isinstance(value, dict):
        return clean_text(value.get('name') or value.get('@id') or '')
    if isinstance(value, list):
        return text_of(value[0]) if value else ''
    return clean_text(str(value or ''))


def parse_address(address):
    '''Return (location, alpha3 country) from a schema.org address.'''
    if not isinstance(address, dict):
        return text_of(address), ''
    country_text = text_of(address.get('addressCountry'))
    country = to_alpha3(country_text)
    parts = [
        text_of(address.get('addressLocality')),
        text_of(address.get('addressRegion')),
        country_name(country) or country_text]
    return ', '.join(p for p in parts if p), country


def event_to_row(item, source):
    location, venue, country = '', '', ''
    places = item.get('location') or []
    for place in places if isinstance(places, list) else [places]:
        if isinstance(place, str):
            location = location or place
        elif not isinstance(place, dict):
            continue
        elif 'VirtualLocation' in str(place.get('@type')):
            location = location or 'Online'
        else:
            venue = venue or text_of(place.get('name'))
            place_location, country = parse_address(place.get('address'))
            location = location or place_location
    if not location and 'Online' in str(item.get('eventAttendanceMode')):
        location = 'Online'
    return {
        'Subject': clean_subject(text_of(item.get('name'))),
        'Start Date': text_of(item.get('startDate'))[:10],
        'End Date': text_of(item.get('endDate'))[:10],
        'Location': clean_location(location),
        'Country': country or country_from_location(location),
        'Venue': venue,
        'Website URL': clean_url(text_of(item.get('url')) or source),
        '_source': source,
        '_method': 'schema.org'}


def find_links(soup, base_url):
    '''Proposal and sponsorship links are not in schema.org,
    so look for obvious anchors.'''
    links = {}
    for anchor in soup.find_all('a', href=True):
        label = f"{anchor.get_text(' ', strip=True)} {anchor['href']}"
        for column, pattern in LINK_PATTERNS.items():
            if column in links or \
                    not re.search(pattern, label, re.IGNORECASE):
                continue
            url = httpx.URL(base_url).join(anchor['href'])
            links[column] = clean_url(str(url))
    return links


def scrape(url, client):
    '''Return every dated event found on the page, newest first.'''
    try:
        response = client.get(url)
        response.raise_for_status()
    except httpx.HTTPError as error:
        return {'url': url, 'error': str(error), 'events': []}
    soup = BeautifulSoup(response.text, 'lxml')
    final_url = str(response.url)
    items = [*iter_jsonld(soup), *iter_microdata(soup)]
    events = [event_to_row(i, final_url) for i in items if is_event(i)]
    if links := find_links(soup, final_url):
        for event in events:
            event.update(links)
    events = [e for e in events if e['Start Date']]
    events.sort(key=lambda e: e['Start Date'], reverse=True)
    title = soup.title.get_text(strip=True) if soup.title else ''
    return {
        'url': url, 'final_url': final_url, 'title': title,
        'links': links, 'events': events}


# ---------- web search ----------

def search(name, max_results=5):
    '''Return result URLs, or None if the search failed.'''
    from ddgs import DDGS
    query = f'{name} python conference {date.today().year}'
    try:
        results = DDGS().text(query, max_results=max_results)
    except Exception as error:  # search backends fail in creative ways
        print(f'search failed for {name!r}: {error}')
        return None
    return [r['href'] for r in results]


# ---------- merge ----------

def add_note(df, index, note):
    old = df.at[index, 'Updates']
    df.at[index, 'Updates'] = f'{old}\n{note}' if old else note


def merge(df, found, min_ratio=0.8):
    '''Fill blanks in matching rows and append editions not yet listed.
    Each change is noted in the row's Updates column and in the log.'''
    df = df.copy()
    # Keep the input order; new editions go after their series' last row
    df['_order'] = range(len(df))
    log = []
    for event in found:
        event_key = base_name(event['Subject'])
        if not event_key or not event['Start Date']:
            continue
        source = event['_source']
        # Match series name + start year, so a new edition gets a new row
        keys = df['Subject'].map(base_name)
        same_series = keys.map(lambda k: is_similar(k, event_key, min_ratio))
        same_year = df['Start Date'].str[:4] == event['Start Date'][:4]
        if (matches := df.index[same_series & same_year]).empty:
            if not same_series.any():
                continue  # search hit for some unrelated event
            last = df.loc[same_series, '_order'].max()
            df.loc[df.index.max() + 1] = {
                c: event.get(c, '') for c in COLUMNS} | {
                'Row': 'new', 'Updates': f'added from {source}',
                '_order': last + 0.001}
            log.append({'action': 'added', 'row': 'new', **event})
            continue
        # Prefer the same start date, then the closest name
        index = max(matches, key=lambda i: (
            df.at[i, 'Start Date'] == event['Start Date'],
            SequenceMatcher(None, df.at[i, 'Subject'].lower(),
                            event['Subject'].lower()).ratio()))
        row = df.at[index, 'Row']
        for column in COLUMNS:
            new, old = event.get(column, ''), df.at[index, column]
            if new and not old:
                df.at[index, column] = new
                add_note(df, index, f'filled {column} from {source}')
                log.append({
                    'action': 'filled', 'row': row,
                    'column': column, 'new': new, **event})
            elif new and old and new != old and \
                    column in [*DATE_COLUMNS, 'Venue']:
                add_note(
                    df, index,
                    f'conflict {column}: {source} says {new}')
                log.append({
                    'action': 'conflict', 'row': row,
                    'column': column, 'old': old, 'new': new, **event})
    # Match the "Conf" convention of each series for new rows only
    new = df['Row'] == 'new'
    subjects, _ = harmonize_conf(df['Subject'])
    df.loc[new, 'Subject'] = subjects[new]
    df = df.sort_values('_order', kind='stable').drop(columns='_order')
    return df, pd.DataFrame(log)


def main():
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument(
        'csv', type=Path, nargs='?',
        default=DRAFTS_FOLDER / 'conferences_clean.csv')
    parser.add_argument('--skip-scrape', action='store_true')
    parser.add_argument('--skip-search', action='store_true')
    parser.add_argument(
        '--limit', type=int, help='only process the first N URLs/series')
    args = parser.parse_args()
    DRAFTS_FOLDER.mkdir(parents=True, exist_ok=True)
    cache_path = DRAFTS_FOLDER / 'cache.json'
    cache = json.loads(cache_path.read_text()) if cache_path.exists() else {}

    df = pd.read_csv(args.csv, dtype=str, keep_default_na=False)
    print(f'{len(df)} rows read')
    if 'Row' not in df:
        df['Row'] = [str(i + 2) for i in df.index]
    df['Updates'] = ''

    found = []
    client = httpx.Client(
        headers=HEADERS, follow_redirects=True, timeout=15)

    def cached_scrape(url):
        if (result := cache.get(url)) is None:
            time.sleep(REQUEST_DELAY)
            if 'error' not in (result := scrape(url, client)):
                cache[url] = result  # failures are retried next run
        return result

    with client:
        # 1. Scrape each unique URL in the dataset
        if not args.skip_scrape:
            urls = [u for u in df['Website URL'].unique() if u]
            urls = urls[:args.limit]
            for i, url in enumerate(urls, 1):
                found += cached_scrape(url)['events'][:1]
                if i % 50 == 0:
                    print(f'scraped {i}/{len(urls)}')
                    cache_path.write_text(json.dumps(cache))

        # 2. Search each conference series once and scrape the top hits
        if not args.skip_search:
            latest = df.sort_values('Start Date').groupby(
                df['Subject'].map(base_name))['Subject'].last()
            names = [YEAR.sub('', n).strip() for n in latest]
            names = names[:args.limit]
            for i, name in enumerate(names, 1):
                search_key = f'search:{name}'
                if (urls := cache.get(search_key)) is None:
                    time.sleep(REQUEST_DELAY)
                    if (urls := search(name)) is not None:
                        cache[search_key] = urls
                results = [cached_scrape(url) for url in urls or []]
                events = [
                    e for r in results for e in r['events']
                    if is_similar(
                        base_name(e['Subject']), base_name(name), 0.8)]
                newest = max(
                    events, key=lambda e: e['Start Date'], default=None)
                if newest:
                    found.append(newest)
                if i % 25 == 0:
                    print(f'searched {i}/{len(names)}')
                    cache_path.write_text(json.dumps(cache))

    cache_path.write_text(json.dumps(cache))
    df, log = merge(df, found)
    comments = [c for c in ('Issues', 'Duplicates') if c in df]
    df = df[['Row', *COLUMNS, *comments, 'Updates']]
    df.to_csv(DRAFTS_FOLDER / 'conferences_updated.csv', index=False)
    write_ods(df, DRAFTS_FOLDER / 'conferences_updated.ods')
    if not log.empty:
        log.to_csv(DRAFTS_FOLDER / 'updates.csv', index=False)
        print(log['action'].value_counts().to_string())
    print(f'{len(df)} rows written to {DRAFTS_FOLDER.resolve()}')


if __name__ == '__main__':
    main()
